### ISSUE TITLE
update to DPoP authentication. Legacy being deprecated.

### ISSUE THREAD

**Issue by ewingson** [NoelDeMartin/solid-focus#12]
Solid recently had an update from legacy auth to the use of DPoP auth.

We noticed that your app still is using the old auth.

We'd like to encourage you to switch to the new auth using the Demonstrating Proof of Posession technology.

Our motivation for the update was using the standard OIDC-way. 

- CSS is and will only use DPoP.
- For a transition period NSS is able to use both legacy and DPoP.
- SolidOS has been migrated and only uses DPoP.

Javascript libraries using the new authentication methods include :
- [Inrupt's](https://github.com/inrupt/solid-client-authn-js) solid-client-authn-browser for the browser and solid-client-authn-node.
- and [solid-node-client](https://github.com/solid/solid-node-client) for nodejs.
- To obtain a token for nodejs app login, you will also need [Inrupt's generate-oidc-token](https://github.com/inrupt/generate-oidc-token).

Some simple examples of javascript app using the DPoP auth can be found here
- https://github.com/0dataapp/hello/tree/main/solid.
- or https://github.com/jeff-zucker/solid-ide (simple migration).

The list of apps using the new DPoP authorization can be followed here [dpop-status](https://solidproject.solidcommunity.net/Team/dpop-migration).

Just let us know if we can assist you on switching your app at https://gitter.im/solid/app-development or https://forum.solidproject.org

From solid team

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening this issue!

I'm aware that the app doesn't work with the latest authentication, but it may take a while until I update it. I talked about that in my latest update in #10 and I'm already tracking this issue in #12, so I'll close this as a duplicate.
