### ISSUE TITLE
solid-focus tries to load tasks from wrong resources

### ISSUE THREAD

**Issue by angelo-v** [NoelDeMartin/solid-focus#2]
I created new workspaces in my private storage (https://angelo.veltens.org/private). As soon as I reload the page, no data is displayed anymore. A look at the browsers developer tools reveals, that the data is tried to be loaded from the wrong locations:

Instead of `/private/my-workspace` the app tries to load `/my-workspace` and fails of course.

**Comment by angelo-v** [comment]
Yes it does. When you create a workspace, you can select a storage. I added /public as well as /private to my pim:storage relation and both get listed in the selection box on solid-focus

**Comment by NoelDeMartin** [comment]
@angelo-v I've looked into the documentation for `pim:storage` and now I understand it a little bit :D.

After doing so, I've looked at the code and seems like I cannot reproduce your issue, it's working correctly on my end. Could you give more details to reproduce the problem?

In case you want to look at the code, this part [here](https://github.com/NoelDeMartin/solid-focus/blob/master/src/services/backends/SolidBackend.ts#L20...L22) is where the workspaces are loaded:
```js
for (const storageUrl of user.storages) {
    containers.push(... await Solid.getContainers(storageUrl, [TASK_GROUP]));
}
```

As you can see, workspaces are loaded from all storages not only the root. And the list of storages is the same that is used in the form to create workspaces. So if it was shown there, it should be loaded here.

What server are you using? I am using [node-solid-server](https://github.com/solid/node-solid-server) for local development.

**Comment by angelo-v** [comment]
Hi, I am using my own installation of NSS 5. My WebID is https://angelo.veltens.org/profile/card#me

This is how I reproduce it:

1. Visit https://noeldemartin.github.io/solid-focus/#
2. Enter `angelo.veltens.org` and log in.
3. Solid-Focus loads my profile correctly
4. Solid-Focus loads my storage at `https://angelo.veltens.org/private/` (a `ldb:BasicContainer`) correctly
5. This container contains another container with relative ID `<personal/>`
6. Solid-Focus tries to load `https://angelo.veltens.org/personal` instead of `https://angelo.veltens.org/private/personal`

So it seems to use `<personal/>` as a absolute path, instead of a path relative to `</private/>`

**Comment by NoelDeMartin** [comment]
@angelo-v Ok I could reproduce it and fix it :). I haven't released a new version, but you can use the development version to see that the bug is fixed here: https://solid-focus.netlify.com

**Comment by angelo-v** [comment]
Yes, it works thanks!
