### ISSUE TITLE
Renaming Tasks and Lists

### ISSUE THREAD

**Issue by johanbove** [NoelDeMartin/solid-focus#4]
Thank you again for this great example of a Solid app!

I would like to see the functionality to edit Tasks and Lists. Was this something you already had on your plans for this app? Otherwise I would like to see what I can do to make this work.
I'm new at both Solid and TypeScript so this would be an excellent way of learning both concepts better.

**Comment by NoelDeMartin** [comment]
Hi there!

Yes I already had in mind adding that functionality and more, I want to actually have this app replace my current task manager so it needs a lot more functionality :).

At the moment I am working on refactoring the way data is managed, two strong contenders are [LDFlex](https://github.com/RubenVerborgh/LDflex) and [Soukai](https://github.com/noeldemartin/soukai). After that I'll probably get into adding more features, I'm documenting my progress here in case you want to check it out: https://noeldemartin.com/tasks/improving-solid-focus-task-manager

If you want to contribute it's ok, I'm open to accepting PRs. I still haven't decided exactly how other features will work, but at the moment I'm taking a lot of inspiration from my current task manager: [Wunderlist](https://www.wunderlist.com/). So I'll probably have a panel that opens to the right when clicking on a task item, and there will be some advanced options like edition, setting a due date, etc. And I'm trying to use material design principles but not religiously, I use them more as a toolbox than anything else.

**Comment by johanbove** [comment]
Great idea to look at Wunderlist. That's a really good task app. Too bad $MS decided that MS Todo will be developed further instead... A new panel would make sense yes, especially in regards to future extensions of what can be done with the tasks.

**Comment by NoelDeMartin** [comment]
I just release a new version including these features and more, like task scheduling :).

**Comment by johanbove** [comment]
Awesome. Thanks!
